In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import os
import requests
from dotenv import load_dotenv
from pathlib import Path
import pandas as pd

In [3]:
env_path = Path("..") / "backend" / "app" / ".env"   # relative to Notebooks/
load_dotenv(dotenv_path=env_path)

True

In [4]:
api_key = os.getenv("AV_API_KEY")
print(api_key)

YV04LNOO150FFVJZ

In [5]:
url = (
                "https://www.alphavantage.co/query?"
                "function=TIME_SERIES_DAILY&"
                f"symbol={'MSFT'}&"
                f"outputsize={'compact'}&"
                "datatype=json&"
                f"apikey={api_key}"
            )
response = requests.get(url)
response_data = response.json()

In [6]:
response_data.keys()

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [6]:
pd.DataFrame(response_data['Time Series (Daily)']).T

             1. open   2. high    3. low  4. close 5. volume
2026-02-10  419.8000  423.6800  412.7000  413.2700  44790857
2026-02-09  404.8500  414.8900  400.8700  413.6000  45480526
2026-02-06  399.1650  401.7900  392.9200  401.1400  53515311
2026-02-05  407.4400  408.3000  392.3200  393.6700  66289247
2026-02-04  411.0000  419.8000  409.2400  414.1900  45012374
...              ...       ...       ...       ...       ...
2025-09-24  510.3800  512.4800  506.9200  510.1500  13533711
2025-09-23  513.8000  514.5899  507.3100  509.2300  19799580
2025-09-22  515.5900  517.7400  512.5450  514.4500  20009314
2025-09-19  510.5600  519.3000  510.3100  517.9300  52474093
2025-09-18  511.4900  513.0700  507.6600  508.4500  18913696

[100 rows x 5 columns]

In [8]:
 # Read data into DataFrame (8.1.12 & 8.1.13)
stock_data = response_data['Time Series (Daily)']
df = pd.DataFrame.from_dict(stock_data, orient="index", dtype=float)

# Convert index to `DatetimeIndex` named "date" (8.1.14)
df.index = pd.to_datetime(df.index, format='%Y-%m-%d')
df.index.name = "date"

# Remove numbering from columns (8.1.15)
df.columns = [col.split('. ')[1] for col in df.columns]

In [9]:
df

               open      high      low   close      volume
date
2026-02-09  404.850  414.8900  400.870  413.60  45480526.0
2026-02-06  399.165  401.7900  392.920  401.14  53515311.0
2026-02-05  407.440  408.3000  392.320  393.67  66289247.0
2026-02-04  411.000  419.8000  409.240  414.19  45012374.0
2026-02-03  422.010  422.0500  408.560  411.21  60076532.0
...             ...       ...      ...     ...         ...
2025-09-23  513.800  514.5899  507.310  509.23  19799580.0
2025-09-22  515.590  517.7400  512.545  514.45  20009314.0
2025-09-19  510.560  519.3000  510.310  517.93  52474093.0
2025-09-18  511.490  513.0700  507.660  508.45  18913696.0
2025-09-17  510.620  511.2900  505.930  510.02  15816585.0

[100 rows x 5 columns]

In [12]:
url = (
                "https://www.alphavantage.co/query?"
                "function=TIME_SERIES_DAILY_ADJUSTED&"
                f"symbol={'MSFT'}&"
                f"outputsize={'compact'}&"
                "datatype=json&"
                f"apikey={api_key}"
            )
response = requests.get(url)
response_data = response.json()

In [13]:
response_data.keys()

dict_keys(['Information'])

In [14]:
response_data['Information']

'Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints'